version: '3.1'

services:

  web:
    build: ${WEB_DOCKER_PATH}
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${WEB_PATH}:/var/www/html/
    ports:
      - ${WEB_PORT}:80
    working_dir: /var/www/html/

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ${DB_PATH}:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo:
    image: mongo:4.0-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - ${MONGO_DB_PATH}:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

#  composer:
#    image: composer:1.6
#    volumes:
#      - .:/var/www/html/
#    working_dir: /var/www/html/
##    command: composer install
#    command: composer update --ignore-platform-reqs
