version: '3.1'

services:

  web:
    build: ${WEB_DOCKER_PATH}
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${WEB_PATH}:/var/www/html/
    ports:
      - ${WEB_PORT}:80
    working_dir: ${WEB_WORKING_DIR}

  mysql:
    image: mysql:8.0
#    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${DB_PATH}:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${DB_PORT}
    ports:
      - ${PHPMYADMIN_PORT}:80

  mongo:
    image: mongo:4.0-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:27017
    volumes:
      - ${MONGO_DB_PATH}:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_PASSWORD}

  composer:
    image: composer:1.6
    volumes:
      - ${WEB_PATH}:/var/www/html/
    working_dir: ${WEB_WORKING_DIR}
    command: composer update --ignore-platform-reqs
